/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * book.java
 *
 * Created on Aug 26, 2017, 10:58:38 PM
 */

package finaltheoberoiproject;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.Dimension;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author pc
 */
public class book extends javax.swing.JFrame {

    /** Creates new form book */
    public book() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        c2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        r2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox();
        t5 = new javax.swing.JTextField();
        r3 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox();
        t4 = new javax.swing.JTextField();
        r4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        c44 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        res = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        t3 = new javax.swing.JPasswordField();
        re = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book a Room Here");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Lunch");

        jLabel11.setText("Dinner");

        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        jButton1.setText("Go For it !!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Grading Of food-");

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Breakfast");

        jButton2.setText("Check Total BALANCE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48)
                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        r2.setText("Cave Room");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        jLabel5.setText("No. of Nights");

        jLabel7.setText("Check out (yy-mm-dd)");

        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        r3.setText("Large  Room");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        r1.setText("Small Room");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r5.setText("Non A.C");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        jLabel4.setText("No. of Days");

        jLabel6.setText("Check IN (yy-mm-dd)");

        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        r4.setText("A.C");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(r3)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(58, 58, 58))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(r1)
                                    .addGap(203, 203, 203)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(r4)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(r2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(r5)))
                        .addGap(238, 238, 238)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r3)
                    .addComponent(r1)
                    .addComponent(r2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r4)
                    .addComponent(r5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setText("Room No");

        jLabel2.setText("Name");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finaltheoberoiproject/back-arrow.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Book A ROOM NOW !!!!");

        p1.setVisible(false);
        p1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel12.setText("Payments");

        c44.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Payment Method", "Cash", "Punjab National Bank", "Oriental Bank", "ICICI Bank", "Paytm", "Paypal", "HDFC Bank", "Union Bank", "Axis Bank", "Dena Bank" }));
        c44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c44ActionPerformed(evt);
            }
        });

        jLabel13.setText("Select Payment Method");

        jLabel14.setText("Account no.");

        jLabel15.setText("Net Bankiing Password");

        jLabel16.setText("Aadhar Id");

        jButton3.setText("Checkout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ex.setText("EXIT");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });

        res.setText("Reset All");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });

        jLabel18.setText("Contact No.");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(res)
                .addGap(243, 243, 243)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt))
                .addGap(185, 185, 185)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15))
                .addGap(12, 12, 12)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(45, 45, 45)
                .addComponent(c44, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(385, 385, 385))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ex)
                            .addComponent(res))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        re.setText("RESET");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });

        b1.setText("Exit");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Software Developed by - Ashwin Saxena");

        jButton4.setText("Print a Bill");
        jButton4.setToolTipText("Do You wanna Print the Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        new Thread ()
        {
            public void run ()
            {while(true)
                {
                    Calendar cal= new GregorianCalendar();

                    int h = cal .get(Calendar.HOUR);
                    int m = cal .get(Calendar.MINUTE);
                    int s = cal .get(Calendar.SECOND);
                    int a = cal .get(Calendar.AM_PM);
                    String x="";
                    if (a==1 ){x="PM";}
                    else{x="AM";}

                    String net = h+":"+m+":"+s+" "+x;
                    l1.setText(net);
                }

            }

        }.start();
        l1.setFont(new java.awt.Font("DS-Digital", 0, 18)); // NOI18N
        l1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59)
                                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(241, 241, 241)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(re)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(309, 309, 309)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(re)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jLabel17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
p1.setVisible(true);
re.setVisible(false);
b1.setVisible(false);


// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // room checking start
        String NAMME = t6.getText();
        String no = t7.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
            Statement stmt = con.createStatement();
            String query = "Select name FROM room_check WHERE room='"+no+"';";
            ResultSet rs = stmt.executeQuery(query);
            if(rs.next()) {
                String name = rs.getString("Name");

                JOptionPane.showMessageDialog(null,"Room   "  +no+ "  is already reserved by   "+ " "+name);

            } else {JOptionPane.showMessageDialog(null,"Congrats !!! room available");


            }

            rs.close();
            stmt.close();
            con.close();

        } catch (Exception e){

            JOptionPane.showMessageDialog(this,e.getMessage());


        }



      {double Total=0;


        if (r1.isSelected())
            Total=Total+1000;
        if (r2.isSelected())
            Total=Total+1500;
        if (r3.isSelected())
            Total=Total+2000;
        if (r4.isSelected())
            Total=Total+100;
        if (r5.isSelected())
            Total=Total+00;

        if (c1.getSelectedIndex()==0)
            Total=Total+150;
        if (c1.getSelectedIndex()==1)
            Total=Total+100;
        if (c1.getSelectedIndex()==2)
            Total=Total+80;
        if (c2.getSelectedIndex()==0)
            Total=Total+150;
        if (c2.getSelectedIndex()==1)
            Total=Total+110;
        if (c2.getSelectedIndex()==2)
            Total=Total+100;

        if (c3.getSelectedIndex()==0)
            Total=Total+300;
        if (c3.getSelectedIndex()==1)
            Total=Total+250;
        if (c3.getSelectedIndex()==2)
            Total=Total+200;

        if (c4.getSelectedIndex()==0)
            Total=Total*1;
        if (c4.getSelectedIndex()==1)
            Total=Total*2;

        if (c4.getSelectedIndex()==2)
            Total=Total*3;

        if (c4.getSelectedIndex()==3)
            Total=Total*4;

        if (c4.getSelectedIndex()==4)
            Total=Total*5;

        if (c4.getSelectedIndex()==5)
            Total=Total*6;

        if (c4.getSelectedIndex()==6)
            Total=Total*7;

        if (c4.getSelectedIndex()==7)
            Total=Total*8;
        if (c4.getSelectedIndex()==8)
            Total=Total*9;

        if (c4.getSelectedIndex()==9)
            Total=Total*10;



        t1.setText(Double.toString(Total));

      } // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Home frame2 = new Home();
        frame2.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String NE = t6.getText();String no = t7.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
            Statement stmt = con.createStatement();

            String query2 = "INSERT INTO room_check VALUES('"+NE+"','"+no+"');";
            stmt.executeUpdate(query2);
        } catch (Exception e){



        }




        //days selection

  int d; String k =t4.getText();String query="";String up="";
        switch(c4.getSelectedIndex())
        {
        case 0:query = "INSERT INTO converter VALUES('"+k+"',1,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = outdate+day;";


        break;
        case 1 :query = "INSERT INTO converter VALUES('"+k+"',2,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 2 : query = "INSERT INTO converter VALUES('"+k+"',3,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 3 :query = "INSERT INTO converter VALUES('"+k+"',4,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 4 :query = "INSERT INTO converter VALUES('"+k+"',5,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 5 :query = "INSERT INTO converter VALUES('"+k+"',6,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 6 :query = "INSERT INTO converter VALUES('"+k+"',7,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 7:query = "INSERT INTO converter VALUES('"+k+"',8,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 8 :query = "INSERT INTO converter VALUES('"+k+"',9,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
        case 9:query = "INSERT INTO converter VALUES('"+k+"',10,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";

        break;
            default:query = "INSERT INTO converter VALUES('"+k+"',1,'"+k+"','"+no+"','"+NE+"');";
        up="UPDATE converter SET outdate = date+day;";




        }

        ////////////////////////



       



 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/theoberoi","root","ashwin21");
        Statement stmt = con.createStatement();


stmt.executeUpdate(query);
stmt.executeUpdate(up);
}
catch ( Exception f)
{
JOptionPane.showMessageDialog(null,"error");

}




     


        ////////////////////////



 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/theoberoi","root","ashwin21");
        Statement stmt = con.createStatement();
String query4 = "Select outdate FROM converter";
ResultSet rs= stmt.executeQuery(query4);
while(rs.next())
{ Date out = rs.getDate("outdate");

 t5.setText(" "+out);
}



 }
catch ( Exception f)
{

}

/////FACULTY PLANNED
String ser ;
        if(r1.isSelected()||r2.isSelected())
        {
        ser="Yes";

        }
        else ser="No";

String h;

switch(c1.getSelectedIndex())

{
    case 0:h="A";
break;
    case 1:h="B";
    break;
   case 2:h="C";
break;
    default:h="A";

}

String l;
switch(c2.getSelectedIndex())
{
    case 0:l = "A";

break;
    case 1:l="B";
    break;
   case 2:l="C";
break;
    default:l="A";


}


String dd;
switch(c3.getSelectedIndex())
{
    case 0:dd = "A";

break;
    case 1:dd="B";
    break;
   case 2:dd="C";
break;
    default:dd="A";



}

//connectivity now
String c =t4.getText();String o= t5.getText();
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
Statement stmt = con.createStatement();
String queryy = "INSERT INTO faculty VALUES('"+no+"','"+NE+"','"+h+"','"+l+"','"+dd+"','"+ser+"','"+c+"','"+o+"');";

stmt.executeUpdate(queryy);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Error in faculty");




}


//promo code

///////////////////////////reciepts
String typ="";
String status ="";


switch(c44.getSelectedIndex())
{
    case 0:   JOptionPane.showMessageDialog(null,"Please select Payment method");
            break;
    case 1:typ="Cash";status="Done!!";
            break;
    case 2:  typ="Punjab National Bank";status="Done!!";
    break;
    case 3 : typ="Oriental Bank";status="pending";
    break;
    case 4 : typ="ICICI Bank";status="Done!!";
    break;
    case 5:typ="Paytm";status="Done!!";
    break;
    case 6:typ="Paypal";status="pending";
    break;
    case 7 :typ="HDFC Bank,";status="Done!!";
    break;
    case 8:typ="Union Bank";status="pending";
    break;
    case 9:typ="Axis Bank";status="Done!!";
    break;
    case 10:typ="Dena Bank";status="Done!!";
   break;
    default:  JOptionPane.showMessageDialog(null,"Please select Payment method");


}
String id = tt.getText();

String ac = t8.getText();
String pas = t3.getText();
String contact = (cn.getText());

try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
Statement stmt = con.createStatement();
String queryyy = "INSERT INTO rec VALUES('"+NE+"','"+no+"','"+id+"','"+typ+"','"+status+"','"+ac+"','"+pas+"','"+contact+"');";

stmt.executeUpdate(queryyy);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Error in reciept");
}



///////////////////////history

int hh = Integer.parseInt(t7.getText());
String bh = t6.getText();
String ci = t4.getText();
String co = t5.getText();


try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
Statement stmt = con.createStatement();
String querysyy = "INSERT INTO history VALUES('"+hh+"','"+bh+"','"+ci+"','"+co+"');";

stmt.executeUpdate(querysyy);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Error in historyt");
}







    
        String bn="" ;
        if(r1.isSelected())
        {bn="small";}
        else if(r2.isSelected())
        {bn="cave";}
        else
             if(r3.isSelected())
        {bn="Large";}
int day =0;

switch(c4.getSelectedIndex())
{
    case 0: day= 1;
    break;

    case 1: day= 2;
    break;

    case 2: day= 3;
    break;

    case 3: day= 4;
    break;

    case 4: day= 5;
    break;

    case 5: day= 6;
    break;

    case 6: day= 7;
    break;

    case 7: day= 8;
    break;

    case 8: day= 9;
    break;

    case 9: day= 10;
    break;
    default:
     day= 1;

}
String tyep="";
if(r4.isSelected())
{
 tyep="A.C";
}else
  if(r5.isSelected())
  { tyep="Non A.C";
  }





///////////



try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
Statement stmt = con.createStatement();
String queryyy = "INSERT INTO bill VALUES('"+t6.getText()+"','"+t7.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+h+"','"+l+"','"+dd+"','"+day+"','"+tyep+"','"+bn+"','"+tt.getText()+"','"+typ+"','"+t1.getText()+"');";

stmt.executeUpdate(queryyy);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Error in billun reciept");
}

int re; 
re = JOptionPane.showConfirmDialog(null,"Room for "+t6.getText() +"is Booked with Room No." +t7.getText() +"\n"+"Check Out date Is "+t5.getText()+"\n"+"\n"+"Do You want to print the reciept  ","Confirm",JOptionPane.YES_NO_OPTION );
if (re==0)
{bill frame28 = new bill();
frame28.setVisible(true);
this.setVisible(false);

}else
    if(re==1)
    {

    }


// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed

        int more;



        more= JOptionPane.showConfirmDialog(null,"Are you sure","Confirm" ,JOptionPane.YES_NO_OPTION);
        if(more==0) {
            System.exit(0);

        }

        else
            if(more==1) {
            }



        // TODO add your handling code here:
}//GEN-LAST:event_exActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        book frame2 = new book();
        frame2.setVisible(true);
        this.setVisible(false);


        // TODO add your handling code here:
}//GEN-LAST:event_resActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
r1.setEnabled(false);
r3.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
r2.setEnabled(false);r3.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
r1.setEnabled(false);r2.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
r4.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_r5ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
r5.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_r4ActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
     book frame2 = new book();
        frame2.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_reActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
System.exit(0);
// TODO add your handling code here:
}//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c44ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_c44ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
bill frame28 = new bill();
frame28.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JComboBox c44;
    private javax.swing.JComboBox c5;
    private javax.swing.JTextField cn;
    private javax.swing.JButton ex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JPanel p1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JButton re;
    private javax.swing.JButton res;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables

}
