/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Booking_Centre.java
 *
 * Created on Jan 1, 2002, 12:41:40 AM
 */

package finaltheoberoiproject;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Booking_Centre extends javax.swing.JFrame {

    /** Creates new form Booking_Centre */
    public Booking_Centre() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        t1 = new javax.swing.JTextField();
        c3 = new javax.swing.JComboBox();
        ch2 = new javax.swing.JCheckBox();
        t2 = new javax.swing.JTextField();
        ce = new javax.swing.JButton();
        res = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        c44 = new javax.swing.JComboBox();
        py = new javax.swing.JLabel();
        ll = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        ll99 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        t9 = new javax.swing.JTextField();
        lo = new javax.swing.JLabel();
        tt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Check In Date  (yy-mm-dd)");

        jLabel6.setText("Breakfast");

        jLabel3.setText("Day");

        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        r4.setText("A.C");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        r5.setText("NON A.C");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        jLabel8.setText("CheckOut Date");

        jLabel4.setText("Night");

        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButton2.setText("Check Total BALANCE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A GRADE", "B GRADE", "C GRADE" }));

        jLabel7.setText("Lunch");

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A GRADE", "B GRADE", "C GRADE" }));

        jLabel5.setText("Dinner");

        r1.setText("Small Room ");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setText("Cave Room");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setText("Large Room");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        t1.setEditable(false);

        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A GRADE", "B GRADE", "C GRADE" }));

        ch2.setVisible(false);
        ch2.setText("Did YOU have a Promo Code");
        ch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2ActionPerformed(evt);
            }
        });

        t2.setVisible(false);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        ce.setVisible(false);
        ce.setText("CHECKOUT ");
        ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceActionPerformed(evt);
            }
        });

        res.setText("Reset All");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });

        ex.setText("EXIT");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36));
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("ROOM BOOKING CENTER");

        jLabel9.setText("Name");

        jLabel11.setText("Room No");

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        jButton1.setText("GO FOR it !!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        c44.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Payment Method", "Cash", "Punjab National Bank", "Oriental Bank", "ICICI Bank", "Paytm", "Paypal", "HDFC Bank", "Union Bank", "Axis Bank", "Dena Bank" }));
        c44.setVisible(false);

        py.setFont(new java.awt.Font("Bell MT", 3, 24));
        py.setForeground(new java.awt.Color(51, 51, 255));
        py.setText("Payment");
        py.setVisible(false);

        ll.setText("Payment Method");
        ll.setVisible(false);

        l13.setVisible(false);
        l13.setText("Account no.");

        ll99.setText("Net Banking Password");
        ll99.setRequestFocusEnabled(false);
        ll99.setVisible(false);

        t3.setVisible(false);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t8.setVisible(false);
        t8.setRequestFocusEnabled(false);
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        jLabel10.setText("Developed by-Ashwin Saxena");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finaltheoberoiproject/back-arrow.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        t9.setVisible(false);

        lo.setVisible(false);
        lo.setText("Residential Id");

        tt.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(res)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton2)
                                                        .addComponent(jLabel2))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(66, 66, 66)
                                                .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton1)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(89, 89, 89)
                                                        .addComponent(r4)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(90, 90, 90)
                                                        .addComponent(r2)
                                                        .addGap(113, 113, 113)
                                                        .addComponent(r3))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(r5)
                                                        .addGap(140, 140, 140))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25)))))))
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c44, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(215, 215, 215))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(ch2)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(l13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(72, 72, 72)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ll99)
                                                    .addComponent(lo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(py, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tt)
                                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(ce)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r1)
                            .addComponent(r3)
                            .addComponent(r2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r4)
                            .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(res)
                    .addComponent(ex)
                    .addComponent(py))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ll99))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lo))
                .addGap(18, 18, 18)
                .addComponent(ce)
                .addGap(42, 42, 42)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed

        r5.setEnabled(false);


        // TODO add your handling code here:
}//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        r4.setEnabled(false);        // TODO add your handling code here:
}//GEN-LAST:event_r5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
// room checking start
String NAMME = t6.getText();
        String no = t7.getText();
      try{
      Class.forName("java.sql.Driver");
      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
      Statement stmt = con.createStatement();
      String query = "Select name FROM room_check WHERE room='"+no+"';";
ResultSet rs = stmt.executeQuery(query);
if(rs.next())
{
String name = rs.getString("Name");

JOptionPane.showMessageDialog(null,"Room   "  +no+ "  is already reserved by   "+ " "+name);
    
}
else {JOptionPane.showMessageDialog(null,"Congrats !!! room available");


}

rs.close();
stmt.close();
con.close();

      }
catch (Exception e){

JOptionPane.showMessageDialog(this,e.getMessage());


}



{double Total=0;


        if (r1.isSelected())
            Total=Total+1000;
        if (r2.isSelected())
            Total=Total+1500;
        if (r3.isSelected())
            Total=Total+2000;
        if (r4.isSelected())
            Total=Total+100;
        if (r5.isSelected())
            Total=Total+00;
      
        if (c1.getSelectedIndex()==0)
            Total=Total+150;
        if (c1.getSelectedIndex()==1)
            Total=Total+100;
        if (c1.getSelectedIndex()==2)
            Total=Total+80;
        if (c2.getSelectedIndex()==0)
            Total=Total+150;
        if (c2.getSelectedIndex()==1)
            Total=Total+110;
        if (c2.getSelectedIndex()==2)
            Total=Total+100;

        if (c3.getSelectedIndex()==0)
            Total=Total+300;
        if (c3.getSelectedIndex()==1)
            Total=Total+250;
        if (c3.getSelectedIndex()==2)
            Total=Total+200;

        if (c1.getSelectedIndex()==0)
            Total=Total*1;
        if (c1.getSelectedIndex()==1)
            Total=Total*2;

        if (c1.getSelectedIndex()==2)
            Total=Total*3;

        if (c1.getSelectedIndex()==3)
            Total=Total*4;

        if (c1.getSelectedIndex()==4)
            Total=Total*5;

        if (c1.getSelectedIndex()==5)
            Total=Total*6;

        if (c1.getSelectedIndex()==6)
            Total=Total*7;

        if (c1.getSelectedIndex()==7)
            Total=Total*8;
        if (c1.getSelectedIndex()==8)
            Total=Total*9;

        if (c1.getSelectedIndex()==9)
            Total=Total*10;



        t1.setText(Double.toString(Total));




}



//date as string



        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        r2.setEnabled(false);
        r3.setEnabled(false);

        // TODO add your handling code here:
}//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        r1.setEnabled(false);
        r3.setEnabled(false);

        // TODO add your handling code here:
}//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        r1.setEnabled(false);
        r2.setEnabled(false);

        // TODO add your handling code here:
}//GEN-LAST:event_r3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ch2.setVisible(true);
c44.setVisible(true);
py.setVisible(true);
t2.setVisible(true);
t8.setVisible(true);
ce.setVisible(true);


       t3.setVisible(true);
ll.setVisible(true);
ll99.setVisible(true);
l13.setVisible(true);
lo.setVisible(true);
tt.setVisible(true);


res.setVisible(true);
ex.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed

int more;



      more= JOptionPane.showConfirmDialog(null,"Are you sure","Confirm" ,JOptionPane.YES_NO_OPTION);
    if(more==0)
    {
    System.exit(0);

    }

    else
    if(more==1)
    {}      



        // TODO add your handling code here:
}//GEN-LAST:event_exActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t3ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t8ActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceActionPerformed
        String NE = t6.getText();String no = t7.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
            Statement stmt = con.createStatement();

            String query2 = "INSERT INTO room_check VALUES('"+NE+"','"+no+"');";
            stmt.executeUpdate(query2);
        } catch (Exception e){



        }




        //days selection

        int d;
        switch(c4.getSelectedIndex())
        {
        case 0:d=1;
        break;
        case 1 :d=2;
        break;
        case 2 : d=3;
        break;
        case 3 :d=4;
        break;
        case 4 :d=5;
        break;
        case 5 :d=6;
        break;
        case 6 : d=7;
        break;
        case 7:d=8;
        break;
        case 8 :d=9;
        break;
        case 9:d=10;
        break;
            default:d=1;



        }

        ////////////////////////
       


        String k =t4.getText();



 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/theoberoi","root","ashwin21");
        Statement stmt = con.createStatement();
String query = "INSERT INTO converter VALUES('"+k+"','"+d+"','"+k+"','"+no+"','"+NE+"');";

stmt.executeUpdate(query);

}
catch ( Exception f)
{
JOptionPane.showMessageDialog(null,"error");

}

         try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/theoberoi","root","ashwin21");
        Statement stmt = con.createStatement();

String yy = "UPDATE converter SET outdate = date+day WHERE day = '"+d+"';";


stmt.executeUpdate(yy);
}
catch ( Exception fnj)
{
JOptionPane.showMessageDialog(null,"big error");

}

        
        
        ////////////////////////

 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/theoberoi","root","ashwin21");
        Statement stmt = con.createStatement();
String query = "Select outdate FROM converter";
ResultSet rs= stmt.executeQuery(query);
while(rs.next())
{ Date out = rs.getDate("outdate");

 t5.setText(" "+out);
}


 
 }
catch ( Exception f)
{

}

/////FACULTY PLANNED
String ser ;
        if(r1.isSelected()||r2.isSelected())
        {
        ser="Yes";
        
        }
        else ser="No";

String h;

switch(c1.getSelectedIndex())

{
    case 0:h="A";
break;
    case 1:h="B";
    break;
   case 2:h="C";
break;
    default:h="A";

}

String l;
switch(c2.getSelectedIndex())
{
    case 0:l = "A";

break;
    case 1:l="B";
    break;
   case 2:l="C";
break;
    default:l="A";


}


String dd;
switch(c3.getSelectedIndex())
{
    case 0:dd = "A";

break;
    case 1:dd="B";
    break;
   case 2:dd="C";
break;
    default:dd="A";



}

//connectivity now

try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
Statement stmt = con.createStatement();
String queryy = "INSERT INTO faculty VALUES('"+no+"','"+NE+"','"+h+"','"+l+"','"+dd+"','"+ser+"');";

stmt.executeUpdate(queryy);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Error in faculty");




}


//promo code

///////////////////////////reciepts
String typ="";
String status ="";


switch(c44.getSelectedIndex())
{
    case 0:   JOptionPane.showMessageDialog(null,"Please select Payment method");
            break;
    case 1:typ="Cash";status="Done!!";
            break;
    case 2:  typ="Punjab National Bank";status="Done!!";
    break;
    case 3 : typ="Oriental Bank";status="pending";
    break;
    case 4 : typ="ICICI Bank";status="Done!!";
    break;
    case 5:typ="Paytm";status="Done!!";
    break;
    case 6:typ="Paypal";status="pending";
    break;
    case 7 :typ="HDFC Bank,";status="Done!!";
    break;
    case 8:typ="Union Bank";status="pending";
    break;
    case 9:typ="Axis Bank";status="Done!!";
    break;
    case 10:typ="Dena Bank";status="Done!!";
   break;
    default:  JOptionPane.showMessageDialog(null,"Please select Payment method");


}
String id = tt.getText();
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theoberoi","root","ashwin21");
Statement stmt = con.createStatement();
String queryy = "INSERT INTO faculty VALUES('"+NE+"','"+no+"','"+id+"','"+typ+"','"+status+"');";

stmt.executeUpdate(queryy);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Error in reciept");



}
   
        // TODO add your handling code here:
}//GEN-LAST:event_ceActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

    private void ch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Home frame2 = new Home();
        frame2.setVisible(true); 
        this.setVisible(false);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
Booking_Centre frame2 = new Booking_Centre();
frame2.setVisible(true);
this.setVisible(false);


        // TODO add your handling code here:
}//GEN-LAST:event_resActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking_Centre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JComboBox c44;
    private javax.swing.JComboBox c5;
    private javax.swing.JButton ce;
    private javax.swing.JCheckBox ch2;
    private javax.swing.JButton ex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel ll;
    private javax.swing.JLabel ll99;
    private javax.swing.JLabel lo;
    private javax.swing.JLabel py;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JButton res;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables

}
